name: fresh_ape_test

plugins:
  - name: solidity
  - name: hardhat
  - name: etherscan
  - name: foundry

dependencies:
  - name: uniswap-core
    github: Uniswap/v3-core
    ref: v1.0.0
  - name: uniswap-periphery
    github: Uniswap/v3-periphery
    ref: v1.3.0
    config_override:
      dependencies:
        - name: openzeppelin
          github: OpenZeppelin/openzeppelin-contracts
          version: 3.4.2
